api: Support assigning qualified qmlelem to a property
qmlweb/qmlweb-parser pull request #18
Opened 2016-07-05 16:21 UTC by stephenmdangelo

e.g.

import QtQuick 2.5 as QQ

Repeater {
  delegate: QQ.Rectangle {}
}

2016-12-26 22:57 UTC, ChALkeR commented
Sorry for not looking at this earlier.

This shouldn't change the existing testcase (removing the test that we already have, i.e. `property Item item: Item {}`). Instead, it should introduce a new one.

In this specific case either _adding_ a new `import` line and adding some new properties to `Properties.qml` or adding an entirely new file would work.

2016-12-26 23:02 UTC, ChALkeR commented
Also I think that this comment by @akreuzkamp: https://github.com/qmlweb/qmlweb-parser/pull/17#issuecomment-231526384 is also applicable to this PR.
Shouldn't the names be converted to proper AST? For example, see [/ImportsNamed.qml](https://github.com/qmlweb/qmlweb-parser/blob/master/tests/qml/ImportsNamed.qml) and [ImportsNamed.qml.json](https://github.com/qmlweb/qmlweb-parser/blob/master/tests/qml/ImportsNamed.qml.json) files.

2016-12-26 23:13 UTC, ChALkeR requested changes
`qmlelem` format changed in 6e5bf1ca2eacb2758c45d5789499d8d0b9cfcb3c, and those strings are now parsed deeper.

This PR should adapt to those changes after a rebase.
Also, it shouldn't remove the existing testcase for `property Item item: Item {}`.

2016-12-26 23:13 UTC, ChALkeR commented on tests/qml/Properties.qml.json
> +    "QQ.Rectangle",
This is not the proper format for `qmlelem`. See [ImportsNamed.qml.json#L27-L32](https://github.com/qmlweb/qmlweb-parser/blob/master/tests/qml/ImportsNamed.qml.json#L27-L32) for how qualified `qmlelem` should be encoded. You could also test with longer paths. e.g. `Abc.Def.Rectangle`.

2016-12-26 23:13 UTC, ChALkeR commented on tests/qml/Properties.qml.json
> +            "QQ.Item",
This is not the proper format for `qmlelem`. See [ImportsNamed.qml.json#L27-L32](https://github.com/qmlweb/qmlweb-parser/blob/master/tests/qml/ImportsNamed.qml.json#L27-L32) for how qualified `qmlelem` should be encoded. You could also test with longer paths. e.g. `Abc.Def.Rectangle`.

2016-12-26 23:13 UTC, ChALkeR commented on tests/qml/Properties.qml
> +  property Item item: QQ.Item {}
This should be added as a new line, and should not replace the current `property Item item: Item {}` test.

2016-12-26 23:13 UTC, ChALkeR commented on tests/qml/Properties.qml
> +QQ.Rectangle {
Unneeded change.

2016-12-26 23:13 UTC, ChALkeR commented on tests/qml/Properties.qml
> +import QtQuick 2.5 as QQ
The original line should be preset to keep the existing testcase (see comment below).
Perhaps use some other import, not `QtQuick`, and add it to the second line?

2016-12-26 23:13 UTC, ChALkeR commented on tests/qml/Properties.qml.json
> +    "QQ.Rectangle",
This has changed and will be `["dot",  "QQ", "Rectangle"],` after a rebase.
Note that this line shouldn't even be present here, as `Rectangle` → `QQ.Rectangle` is an unrelated change on this line.

2016-12-26 23:15 UTC, ChALkeR commented
@stephenmdangelo, sorry for not reviewing at this earlier. In general, I'm in favor of this PR (and thanks for doing this!), but it requires some changes before landing. See the review above.

2017-01-02 18:35 UTC, stephenmdangelo commented
@ChALkeR So I've cleaned up the Properties.json test (as well, I added a change to `tape.js` to fix the tests failing of, say, I was editing in vi).

I think I'm generating the dot expression as you're suggesting.

Though I find it odd that the `expr` as returned by `maybe_assign` is of the form:

```
[
  "dot",
  "DOM",
  [
    "name",
    "DOM"
  ],
  "Div"
]
```
But a non-assigned `qmlelem` (as in `ImportsNamed.qml`) omits the `name` array:

```
[
   "dot",
   "DOM",
   "Div"
]
```

So I went with the latter form. Is this correct? If so, why don't we use the `name` format, or why does that format get returned by `maybe_assign`?

2017-01-02 22:40 UTC, ChALkeR commented on tests/tape.js
> +        continue;
Nit: should be above `const filePath`.

2017-01-02 22:47 UTC, ChALkeR approved these changes
LGTM with a nit.

2017-01-02 22:49 UTC, ChALkeR commented
I will take a look at `maybe_assign` a bit later, though. =)

2017-01-03 13:40 UTC, merged